name: FagestProduction

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
    
    - name: Restore dependencies
      run: dotnet restore
     
    - name: Build
      run: dotnet build --configuration Release

    # Adicione outros passos relevantes ao seu fluxo de trabalho aqui

    - name: Test
      run: dotnet test --configuration Release --no-restore

    - name: Add DevExpress
      run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p c1T5lKEk4aNqKHFmGc3dhRvEeOX4eeFwyLsoTBtLEJOK4l7nkP
      
    # Adicione outros passos relevantes ao seu fluxo de trabalho aqui
    - name: Add DevExpresspackages
      run: dotnet add FagestKeyGenerator.WebAPP.csproj package DevExpress.Blazor -v 22.2.6
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      
      


  
